# Copyright 2025 QuantInsti Quantitative Learnings Pvt Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from blueshift.lib.common.sentinels import NotSpecified, Sentinel

from .factors import Factor, CustomFactor
from ..data import BoundColumn, EquityPricing

class Returns(CustomFactor):
    """ calculates the percent change in close price over the given `window_length`"""
    def __init__(self, inputs:list[BoundColumn|Factor]=[EquityPricing.close], window_length:int|Sentinel=NotSpecified) -> None:...
    ...

class PercentChange(CustomFactor):
    """ calculates the percent change in the input term over the given `window_length`"""
    def __init__(self, inputs:list[BoundColumn|Factor], window_length:int) -> None:...
    ...

class DailyReturns(CustomFactor):
    """calculate daily returns. """
    def __init__(self, inputs:list[BoundColumn|Factor]=[EquityPricing.close], window_length:int=2) -> None: ...
    ...

class SimpleMovingAverage(CustomFactor):
    """ compute simple moving averages. """
    def __init__(self, inputs:list[BoundColumn|Factor],window_length:int) -> None:...
    ...

class WeightedAverageValue(CustomFactor):
    """ weighted average of two terms. """
    def __init__(self, inputs:list[BoundColumn|Factor], window_length:int) -> None:...
    ...

class VWAP(WeightedAverageValue):
    """ VWAP factor. """
    def __init__(self, inputs:list[BoundColumn|Factor]=[EquityPricing.close, EquityPricing.volume], 
                 window_length:int|Sentinel=NotSpecified) -> None: ...
    ...

class MaxDrawdown(CustomFactor):
    """ max drawdown factor. """
    def __init__(self, inputs:list[BoundColumn|Factor], window_length:int) -> None:...
    ...

class AverageDollarVolume(CustomFactor):
    """ average traded dollar volume. """
    def __init__(self, inputs:list[BoundColumn|Factor]=[EquityPricing.close, EquityPricing.volume], 
                 window_length:int|Sentinel=NotSpecified) -> None: ...
    ...

class ExponentialWeightedMovingAverage(CustomFactor):
    """ exponentially weighted moving average. """
    def __init__(self, inputs:list[BoundColumn|Factor], window_length:int, decay_rate:float) -> None:...
    ...

class ExponentialWeightedMovingStdDev(CustomFactor):
    """ exponentially weighted moving standard deviation. """
    def __init__(self, inputs:list[BoundColumn|Factor], window_length:int, decay_rate:float) -> None:...
    ...

class LinearWeightedMovingAverage(CustomFactor):
    """ linear weighted moving average. """
    def __init__(self, inputs:list[BoundColumn|Factor], window_length:int) -> None:...
    ...

class AnnualizedVolatility(CustomFactor):
    """ annualized volatility. """
    def __init__(self, inputs:list[BoundColumn|Factor]=[Returns(window_length=2)], window_length:int = 252, 
                 annualization_factor:float=252) -> None: ...
    ...

class PeerCount(CustomFactor):
    """ peer count. """
    def __init__(self, inputs:list[BoundColumn|Factor]) -> None: ...
    ...

class Clip(CustomFactor):
    """clip values in a factor. """
    def __init__(self, inputs:list[BoundColumn|Factor], window_length:int=1, min_bound:float|Sentinel=NotSpecified, 
                 max_bound:float|Sentinel=NotSpecified) -> None:...
    ...

